# Generated by Django 5.1.6 on 2025-03-22 20:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loan", "0002_loan_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loan",
            name="due_date",
        ),
        migrations.RemoveField(
            model_name="repayment",
            name="payment_date",
        ),
        migrations.AddField(
            model_name="repayment",
            name="date_paid",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="loan",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="loan",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("active", "Active"),
                    ("paid", "Paid"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="total_amount_due",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
