# Generated by Django 5.1.6 on 2025-03-23 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loan", "0003_remove_loan_due_date_remove_repayment_payment_date_and_more"),
        ("user", "0004_alter_userprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loans",
                to="user.userprofile",
            ),
        ),
    ]
