# Generated by Django 5.1.6 on 2025-03-24 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loan", "0004_alter_loan_user"),
        ("user", "0005_alter_userprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loans",
                to="user.userprofile",
            ),
        ),
    ]
