# Generated by Django 5.1.6 on 2025-03-22 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_userprofile_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="balance",
            new_name="loan_balance",
        ),
    ]
